=== profiproteomics/proline-server/pm-mascot-parser/src/test/resources/pdi-dataset.dtd
<!ELEMENT dataset (
    ADMIN_INFOS*,
    BIO_SEQUENCE*,
    BIO_SEQUENCE_ANNOTATION*,
    BIO_SEQUENCE_GENE_MAP*,
    BIO_SEQUENCE_RELATION*,
    CHROMOSOME_LOCATION*,
    FASTA_FILE_ENTRY_INDEX*,
    FASTA_PARSING_RULE*,
    GENE*,
    OBJECT_TREE*,
    OBJECT_TREE_SCHEMA*,
    PROTEIN_IDENTIFIER*,
    SCHEMA_VERSION*,
    SEQ_DB_CONFIG*,
    SEQ_DB_ENTRY*,
    SEQ_DB_ENTRY_GENE_MAP*,
    SEQ_DB_ENTRY_OBJECT_TREE_MAP*,
    SEQ_DB_ENTRY_PROTEIN_IDENTIFIER_MAP*,
    SEQ_DB_INSTANCE*,
    SEQ_DB_RELEASE*,
    TAXON*,
    TAXON_EXTRA_NAME*)>

<!ELEMENT ADMIN_INFOS EMPTY>
<!ATTLIST ADMIN_INFOS
    MODEL_VERSION CDATA #REQUIRED
    DB_CREATION_DATE CDATA #IMPLIED
    MODEL_UPDATE_DATE CDATA #IMPLIED
    CHR_LOCATION_UPDATE_TIMESTAMP CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
>

<!ELEMENT BIO_SEQUENCE EMPTY>
<!ATTLIST BIO_SEQUENCE
    ID CDATA #REQUIRED
    ALPHABET CDATA #REQUIRED
    SEQUENCE CDATA #REQUIRED
    LENGTH CDATA #IMPLIED
    MASS CDATA #REQUIRED
    PI CDATA #IMPLIED
    CRC64 CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
>

<!ELEMENT BIO_SEQUENCE_ANNOTATION EMPTY>
<!ATTLIST BIO_SEQUENCE_ANNOTATION
    ID CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    BIO_SEQUENCE_ID CDATA #REQUIRED
    TAXON_ID CDATA #REQUIRED
    OBJECT_TREE_ID CDATA #REQUIRED
    SCHEMA_NAME CDATA #REQUIRED
>

<!ELEMENT BIO_SEQUENCE_GENE_MAP EMPTY>
<!ATTLIST BIO_SEQUENCE_GENE_MAP
    BIO_SEQUENCE_ID CDATA #REQUIRED
    GENE_ID CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    TAXON_ID CDATA #REQUIRED
>

<!ELEMENT BIO_SEQUENCE_RELATION EMPTY>
<!ATTLIST BIO_SEQUENCE_RELATION
    NA_SEQUENCE_ID CDATA #REQUIRED
    AA_SEQUENCE_ID CDATA #REQUIRED
    FRAME_NUMBER CDATA #REQUIRED
>

<!ELEMENT CHROMOSOME_LOCATION EMPTY>
<!ATTLIST CHROMOSOME_LOCATION
    ID CDATA #REQUIRED
    CHROMOSOME_IDENTIFIER CDATA #REQUIRED
    LOCATION CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    GENE_ID CDATA #REQUIRED
    TAXON_ID CDATA #REQUIRED
>

<!ELEMENT FASTA_FILE_ENTRY_INDEX EMPTY>
<!ATTLIST FASTA_FILE_ENTRY_INDEX
    ID CDATA #REQUIRED
    BLOCK_START CDATA #REQUIRED
    BLOCK_LENGTH CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    BIO_SEQUENCE_ID CDATA #REQUIRED
    SEQ_DB_ENTRY_ID CDATA #REQUIRED
    SEQ_DB_INSTANCE_ID CDATA #REQUIRED
>

<!ELEMENT FASTA_PARSING_RULE EMPTY>
<!ATTLIST FASTA_PARSING_RULE
    ID CDATA #REQUIRED
    DB_TYPE CDATA #IMPLIED
    ENTRY_ID CDATA #REQUIRED
    ENTRY_AC CDATA #IMPLIED
    ENTRY_NAME CDATA #REQUIRED
    GENE_NAME CDATA #IMPLIED
    ORGANISM_NAME CDATA #IMPLIED
    TAXON_ID CDATA #IMPLIED
>

<!ELEMENT GENE EMPTY>
<!ATTLIST GENE
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SYNONYMS CDATA #IMPLIED
    ORF_NAMES CDATA #IMPLIED
    IS_ACTIVE CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    TAXON_ID CDATA #REQUIRED
>

<!ELEMENT OBJECT_TREE EMPTY>
<!ATTLIST OBJECT_TREE
    ID CDATA #REQUIRED
    SERIALIZED_DATA CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    SCHEMA_NAME CDATA #REQUIRED
>

<!ELEMENT OBJECT_TREE_SCHEMA EMPTY>
<!ATTLIST OBJECT_TREE_SCHEMA
    NAME CDATA #REQUIRED
    TYPE CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    SCHEMA CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
>

<!ELEMENT PROTEIN_IDENTIFIER EMPTY>
<!ATTLIST PROTEIN_IDENTIFIER
    ID CDATA #REQUIRED
    VALUE CDATA #REQUIRED
    IS_AC_NUMBER CDATA #REQUIRED
    IS_ACTIVE CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    BIO_SEQUENCE_ID CDATA #REQUIRED
    TAXON_ID CDATA #REQUIRED
    SEQ_DB_CONFIG_ID CDATA #REQUIRED
>

<!ELEMENT SCHEMA_VERSION EMPTY>
<!ATTLIST SCHEMA_VERSION
    VERSION CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    TYPE CDATA #REQUIRED
    SCRIPT CDATA #REQUIRED
    CHECKSUM CDATA #IMPLIED
    INSTALLED_BY CDATA #REQUIRED
    INSTALLED_ON CDATA #IMPLIED
    EXECUTION_TIME CDATA #IMPLIED
    STATE CDATA #REQUIRED
    CURRENT_VERSION CDATA #REQUIRED
>

<!ELEMENT SEQ_DB_CONFIG EMPTY>
<!ATTLIST SEQ_DB_CONFIG
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    ALPHABET CDATA #REQUIRED
    REF_ENTRY_FORMAT CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    FASTA_PARSING_RULE_ID CDATA #REQUIRED
    IS_NATIVE CDATA #REQUIRED
>

<!ELEMENT SEQ_DB_ENTRY EMPTY>
<!ATTLIST SEQ_DB_ENTRY
    ID CDATA #REQUIRED
    IDENTIFIER CDATA #REQUIRED
    NAME CDATA #REQUIRED
    VERSION CDATA #IMPLIED
    REF_FILE_BLOCK_START CDATA #IMPLIED
    REF_FILE_BLOCK_LENGTH CDATA #IMPLIED
    IS_ACTIVE CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    BIO_SEQUENCE_ID CDATA #REQUIRED
    TAXON_ID CDATA #REQUIRED
    SEQ_DB_INSTANCE_ID CDATA #REQUIRED
    SEQ_DB_CONFIG_ID CDATA #REQUIRED
>

<!ELEMENT SEQ_DB_ENTRY_GENE_MAP EMPTY>
<!ATTLIST SEQ_DB_ENTRY_GENE_MAP
    SEQ_DB_ENTRY_ID CDATA #REQUIRED
    GENE_ID CDATA #REQUIRED
    SEQ_DB_INSTANCE_ID CDATA #REQUIRED
>

<!ELEMENT SEQ_DB_ENTRY_OBJECT_TREE_MAP EMPTY>
<!ATTLIST SEQ_DB_ENTRY_OBJECT_TREE_MAP
    SEQ_DB_ENTRY_ID CDATA #REQUIRED
    OBJECT_TREE_ID CDATA #REQUIRED
    SCHEMA_NAME CDATA #REQUIRED
>

<!ELEMENT SEQ_DB_ENTRY_PROTEIN_IDENTIFIER_MAP EMPTY>
<!ATTLIST SEQ_DB_ENTRY_PROTEIN_IDENTIFIER_MAP
    SEQ_DB_ENTRY_ID CDATA #REQUIRED
    PROTEIN_IDENTIFIER_ID CDATA #REQUIRED
    SEQ_DB_INSTANCE_ID CDATA #REQUIRED
>

<!ELEMENT SEQ_DB_INSTANCE EMPTY>
<!ATTLIST SEQ_DB_INSTANCE
    ID CDATA #REQUIRED
    FASTA_FILE_PATH CDATA #REQUIRED
    REF_FILE_PATH CDATA #IMPLIED
    IS_INDEXED CDATA #REQUIRED
    IS_DELETED CDATA #REQUIRED
    REVISION CDATA #REQUIRED
    CREATION_TIMESTAMP CDATA #REQUIRED
    SEQUENCE_COUNT CDATA #REQUIRED
    RESIDUE_COUNT CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    SEQ_DB_RELEASE_ID CDATA #IMPLIED
    SEQ_DB_CONFIG_ID CDATA #REQUIRED
>

<!ELEMENT SEQ_DB_RELEASE EMPTY>
<!ATTLIST SEQ_DB_RELEASE
    ID CDATA #REQUIRED
    DATE CDATA #REQUIRED
    VERSION CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
>

<!ELEMENT TAXON EMPTY>
<!ATTLIST TAXON
    ID CDATA #REQUIRED
    SCIENTIFIC_NAME CDATA #REQUIRED
    RANK CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    PARENT_TAXON_ID CDATA #REQUIRED
>

<!ELEMENT TAXON_EXTRA_NAME EMPTY>
<!ATTLIST TAXON_EXTRA_NAME
    ID CDATA #REQUIRED
    CLASS CDATA #REQUIRED
    VALUE CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    TAXON_ID CDATA #REQUIRED
>

=== profiproteomics/proline-server/pm-xtandem-parser/src/test/resources/default_datasets/Proteins_Dataset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "pdi-dataset.dtd">
<dataset>
  <TAXON ID="1" SCIENTIFIC_NAME="root" RANK="no rank" IS_ACTIVE="1" PARENT_TAXON_ID="1"/>
  <TAXON ID="131567" SCIENTIFIC_NAME="cellular organisms" RANK="no rank" IS_ACTIVE="1" PARENT_TAXON_ID="1"/>
  <TAXON ID="2" SCIENTIFIC_NAME="Bacteria" RANK="superkingdom" IS_ACTIVE="1" PARENT_TAXON_ID="131567"/>
  <TAXON ID="1224" SCIENTIFIC_NAME="Proteobacteria" RANK="phylum" IS_ACTIVE="1" PARENT_TAXON_ID="2"/>
  <TAXON ID="32045" SCIENTIFIC_NAME="unclassified Proteobacteria" RANK="no rank" IS_ACTIVE="1" PARENT_TAXON_ID="1224"/>
  <TAXON ID="45359" SCIENTIFIC_NAME="unclassified pseudomonads" RANK="no rank" IS_ACTIVE="1" PARENT_TAXON_ID="32045"/>
  <TAXON ID="306" SCIENTIFIC_NAME="Pseudomonas sp." RANK="species" IS_ACTIVE="1" PARENT_TAXON_ID="45359"/>
  <TAXON ID="74568" SCIENTIFIC_NAME="Pseudomonas sp. ACP" RANK="species" IS_ACTIVE="1" PARENT_TAXON_ID="45359"/>
  <TAXON ID="9481" SCIENTIFIC_NAME="Callithrix" RANK="genus" IS_ACTIVE="1" PARENT_TAXON_ID="1"/>
  <TAXON ID="9483" SCIENTIFIC_NAME="Callithrix jacchus" RANK="species" IS_ACTIVE="1" PARENT_TAXON_ID="9481"/>


  <TAXON_EXTRA_NAME ID="1" CLASS="synonym" VALUE="all" TAXON_ID="1"/>
  <TAXON_EXTRA_NAME ID="2" CLASS="in-part" VALUE="Monera" TAXON_ID="2"/>
  <TAXON_EXTRA_NAME ID="3" CLASS="in-part" VALUE="Procaryotae" TAXON_ID="2"/>
  <TAXON_EXTRA_NAME ID="4" CLASS="in-part" VALUE="Prokaryota" TAXON_ID="2"/>
  <TAXON_EXTRA_NAME ID="5" CLASS="in-part" VALUE="Prokaryotae" TAXON_ID="2"/>
  <TAXON_EXTRA_NAME ID="6" CLASS="blast name" VALUE="bacteria" TAXON_ID="2"/>
  <TAXON_EXTRA_NAME ID="7" CLASS="genbank common name" VALUE="eubacteria" TAXON_ID="2"/>
  <TAXON_EXTRA_NAME ID="8" CLASS="synonym" VALUE="not Bacteria Haeckel 1894" TAXON_ID="2"/>
  <TAXON_EXTRA_NAME ID="9" CLASS="in-part" VALUE="prokaryotes" TAXON_ID="2"/>
  <TAXON_EXTRA_NAME ID="858" CLASS="includes" VALUE="Achromobacter georgiopolitanum" TAXON_ID="306"/>
  <TAXON_EXTRA_NAME ID="859" CLASS="misspelling" VALUE="Pseudomonas sp" TAXON_ID="306"/>
  <TAXON_EXTRA_NAME ID="3770" CLASS="synonym" VALUE="Proteobacteria (as CLASS) Stackebrandt et al. 1988" TAXON_ID="1224"/>
  <TAXON_EXTRA_NAME ID="3771" CLASS="synonym" VALUE="Proteobacteria Garrity et al. 2005" TAXON_ID="1224"/>
  <TAXON_EXTRA_NAME ID="3772" CLASS="synonym" VALUE="not Proteobacteria Cavalier-Smith 2002" TAXON_ID="1224"/>
  <TAXON_EXTRA_NAME ID="3773" CLASS="blast name" VALUE="proteobacteria" TAXON_ID="1224"/>
  <TAXON_EXTRA_NAME ID="3774" CLASS="common name" VALUE="purple bacteria" TAXON_ID="1224"/>
  <TAXON_EXTRA_NAME ID="3775" CLASS="common name" VALUE="purple bacteria and relatives" TAXON_ID="1224"/>
  <TAXON_EXTRA_NAME ID="3776" CLASS="common name" VALUE="purple non-sulfur bacteria" TAXON_ID="1224"/>
  <TAXON_EXTRA_NAME ID="3777" CLASS="common name" VALUE="purple photosynthetic bacteria" TAXON_ID="1224"/>
  <TAXON_EXTRA_NAME ID="3778" CLASS="common name" VALUE="purple photosynthetic bacteria and relatives" TAXON_ID="1224"/>
  <TAXON_EXTRA_NAME ID="52835" CLASS="synonym" VALUE="Pseudomonas sp. (strain ACP)" TAXON_ID="74568"/>
  <TAXON_EXTRA_NAME ID="79142" CLASS="synonym" VALUE="biota" TAXON_ID="131567"/>
  <TAXON_EXTRA_NAME ID="325778" CLASS="uniprot scientific name" VALUE="Pseudomonas sp. (strain ACP)" TAXON_ID="74568"/>

  <FASTA_PARSING_RULE ID="1" ENTRY_ID="1" ENTRY_NAME="PARSING_RULE 1"/>
  <BIO_SEQUENCE ID="171" ALPHABET="AA" SEQUENCE="MNLQRFPRYPLTFGPTPIQPLARLSKHLGGKVHLYAKREDCNSGLAFGGNKTRKLEYLIPEALAQGCDTLVSIGGIQSNQTRQVAAVAAHLGMKCVLVQENWVNYSDAVYDRVGNIQMSRILGADVRLVPDGFDIGFRRSWEDALESVRAAGGKPYAIPAGCSDHPLGGLGFVGFAEEVRAQEAELGFKFDYVVVCSVTGSTQAGMVVGFAADGRADRVIGVDASAKPAQTREQITRIARQTAEKVGLERDIMRADVVLDERFAGPEYGLPNEGTLEAIRLCARTEGMLTDPVYEGKSMHGMIEMVRNGEFPEGSRVLYAHLGGVPALNGYSFIFRDG" LENGTH="338" MASS="36672" PI="6.558" CRC64="01FC286177012FDF"/>
  <BIO_SEQUENCE ID="178" ALPHABET="AA" SEQUENCE="MVHLTGEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMNNPKVKAHGKKVLGAFSDGLTHLDNLKGTFAHLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPVVQAAYQKVVAGVANALAHKYH" LENGTH="147" MASS="16083" PI="6.79" CRC64="FA6F75FEBEAB28BA"/>
  <BIO_SEQUENCE ID="12" ALPHABET="AA"  SEQUENCE="VHLTGEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMNNPKVKAHGKKVLGAFSDGLTHLDNLKGTFAHLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPVVQAAYQKVVAGVANALAHKYH" LENGTH="146" MASS="15952" PI="6.85" CRC64="B3BBDF9B6D1A18BA"/>
  <SEQ_DB_RELEASE ID="33" DATE="20110601" VERSION="2011_06" />
  <SEQ_DB_CONFIG ID="1" NAME="sprot" ALPHABET="AA" REF_ENTRY_FORMAT="SWISS" IS_NATIVE="true" FASTA_PARSING_RULE_ID="1"/>
  <SEQ_DB_CONFIG ID="2" NAME="Dicty_Primary" ALPHABET="AA" REF_ENTRY_FORMAT="SWISS" IS_NATIVE="true" FASTA_PARSING_RULE_ID="1"/>
  <SEQ_DB_INSTANCE ID="33" FASTA_FILE_PATH="H:/Sequences/uniprot/knowledgebase2011_06/uniprot_sprot.fasta" REVISION="1" REF_FILE_PATH="F:/Sequences/sprot/knowledgebase2011_06/uniprot_sprot.dat" IS_INDEXED="1" IS_DELETED="0" CREATION_TIMESTAMP="2011-07-23 12:30:21.000000000" SEQ_DB_CONFIG_ID="1" SEQUENCE_COUNT="4" SEQ_DB_RELEASE_ID="33"/>
  <SEQ_DB_INSTANCE ID="34" FASTA_FILE_PATH="/local/mascot-2.2/sequence/Dicty_Primary/current/dicty_primary_protein_05102009.fas" REVISION="1"  IS_INDEXED="1" IS_DELETED="0" CREATION_TIMESTAMP="2011-07-23 12:30:21.000000000" SEQ_DB_CONFIG_ID="2" SEQUENCE_COUNT="4" SEQ_DB_RELEASE_ID="33"/>
  <GENE ID="228425" NAME="acdS" NAME_TYPE="GENE" IS_ACTIVE="1" TAXON_ID="74568"/>

  <PROTEIN_IDENTIFIER ID="341" VALUE="1A1D_PSESP" IS_AC_NUMBER="0" IS_ACTIVE="0" BIO_SEQUENCE_ID="171" TAXON_ID="306" SEQ_DB_CONFIG_ID="1"/>
  <PROTEIN_IDENTIFIER ID="342" VALUE="Q00740" IS_AC_NUMBER="1" IS_ACTIVE="0" BIO_SEQUENCE_ID="171" TAXON_ID="306" SEQ_DB_CONFIG_ID="1"/>
  <PROTEIN_IDENTIFIER ID="283377" VALUE="1A1D_PSEUD" IS_AC_NUMBER="0" IS_ACTIVE="1" BIO_SEQUENCE_ID="171" TAXON_ID="74568" SEQ_DB_CONFIG_ID="1"/>
  <PROTEIN_IDENTIFIER ID="283378" VALUE="Q00740" IS_AC_NUMBER="1" IS_ACTIVE="1" BIO_SEQUENCE_ID="171" TAXON_ID="74568" SEQ_DB_CONFIG_ID="1"/>
  <PROTEIN_IDENTIFIER ID="23" VALUE="Q6WN28" IS_AC_NUMBER="1" IS_ACTIVE="1" BIO_SEQUENCE_ID="178" TAXON_ID="9483" SEQ_DB_CONFIG_ID="1"/>
  <PROTEIN_IDENTIFIER ID="24" VALUE="HBB_CALJA" IS_AC_NUMBER="0" IS_ACTIVE="1" BIO_SEQUENCE_ID="178" TAXON_ID="9483" SEQ_DB_CONFIG_ID="1"/>

  <SEQ_DB_ENTRY ID="171" IDENTIFIER="1A1D_PSESP" NAME="1-aminocyclopropane-1-carboxylate deaminase" IS_ACTIVE="0" BIO_SEQUENCE_ID="171" TAXON_ID="306" SEQ_DB_INSTANCE_ID="33" SEQ_DB_CONFIG_ID="1"/>
  <SEQ_DB_ENTRY ID="12503699" IDENTIFIER="1A1D_PSEUD" NAME="1-aminocyclopropane-1-carboxylate deaminase" VERSION="1.60" REF_FILE_BLOCK_START="1795457" REF_FILE_BLOCK_LENGTH="4486" IS_ACTIVE="1"  BIO_SEQUENCE_ID="171" TAXON_ID="74568" SEQ_DB_INSTANCE_ID="33" SEQ_DB_CONFIG_ID="1"/>
  <SEQ_DB_ENTRY_GENE_MAP SEQ_DB_ENTRY_ID="12503699" GENE_ID="228425" SEQ_DB_INSTANCE_ID="33"/>
  <SEQ_DB_ENTRY ID="21" IDENTIFIER="HBB_CALJA" NAME="Hemoglobin subunit beta" IS_ACTIVE="1" BIO_SEQUENCE_ID="12" TAXON_ID="9483" SEQ_DB_INSTANCE_ID="33" SEQ_DB_CONFIG_ID="1"/>


  <SEQ_DB_ENTRY_PROTEIN_IDENTIFIER_MAP SEQ_DB_ENTRY_ID="171" PROTEIN_IDENTIFIER_ID="341" SEQ_DB_INSTANCE_ID="33"/>
  <SEQ_DB_ENTRY_PROTEIN_IDENTIFIER_MAP SEQ_DB_ENTRY_ID="171" PROTEIN_IDENTIFIER_ID="342" SEQ_DB_INSTANCE_ID="33"/>
  <SEQ_DB_ENTRY_PROTEIN_IDENTIFIER_MAP SEQ_DB_ENTRY_ID="12503699" PROTEIN_IDENTIFIER_ID="283377" SEQ_DB_INSTANCE_ID="33"/>
  <SEQ_DB_ENTRY_PROTEIN_IDENTIFIER_MAP SEQ_DB_ENTRY_ID="12503699" PROTEIN_IDENTIFIER_ID="283378" SEQ_DB_INSTANCE_ID="33"/>
  <SEQ_DB_ENTRY_PROTEIN_IDENTIFIER_MAP SEQ_DB_ENTRY_ID="21" PROTEIN_IDENTIFIER_ID="23" SEQ_DB_INSTANCE_ID="33"/>
  <SEQ_DB_ENTRY_PROTEIN_IDENTIFIER_MAP SEQ_DB_ENTRY_ID="21" PROTEIN_IDENTIFIER_ID="24" SEQ_DB_INSTANCE_ID="33"/>

</dataset>
