=== profiproteomics/proline-server/pm-mascot-parser/src/test/resources/uds-dataset.dtd
<!ELEMENT dataset (
    ACTIVATION*,
    ADMIN_INFOS*,
    BIOLOGICAL_GROUP*,
    BIOLOGICAL_GROUP_BIOLOGICAL_SAMPLE_ITEM*,
    BIOLOGICAL_SAMPLE*,
    DOCUMENT*,
    ENZYME*,
    ENZYME_CLEAVAGE*,
    EXTERNAL_DB*,
    FRAGMENTATION_RULE*,
    GROUP_SETUP*,
    IDENTIFICATION*,
    IDENTIFICATION_FRACTION*,
    IDENTIFICATION_FRACTION_SUMMARY*,
    IDENTIFICATION_SUMMARY*,
    INSTRUMENT*,
    INSTRUMENT_CONFIG*,
    INSTRUMENT_CONFIG_FRAGMENTATION_RULE_MAP*,
    OBJECT_TREE*,
    OBJECT_TREE_SCHEMA*,
    PEAKLIST_SOFTWARE*,
    PROJECT*,
    PROJECT_DB_MAP*,
    PROJECT_USER_ACCOUNT_MAP*,
    PROTEIN_MATCH_DECOY_RULE*,
    QUANTITATION*,
    QUANTITATION_FRACTION*,
    QUANT_CHANNEL*,
    QUANT_LABEL*,
    QUANT_METHOD*,
    RATIO_DEFINITION*,
    RAW_FILE*,
    RUN*,
    SAMPLE_ANALYSIS_REPLICATE*,
    SCHEMA_VERSION*,
    SPEC_TITLE_PARSING_RULE*,
    THEORETICAL_FRAGMENT*,
    USER_ACCOUNT*,
    VIRTUAL_FOLDER*)>

<!ELEMENT ACTIVATION EMPTY>
<!ATTLIST ACTIVATION
    TYPE CDATA #REQUIRED
>

<!ELEMENT ADMIN_INFOS EMPTY>
<!ATTLIST ADMIN_INFOS
    MODEL_VERSION CDATA #REQUIRED
    DB_CREATION_DATE CDATA #IMPLIED
    MODEL_UPDATE_DATE CDATA #IMPLIED
    CONFIGURATION CDATA #REQUIRED
>

<!ELEMENT BIOLOGICAL_GROUP EMPTY>
<!ATTLIST BIOLOGICAL_GROUP
    ID CDATA #REQUIRED
    NUMBER CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    GROUP_SETUP_ID CDATA #REQUIRED
>

<!ELEMENT BIOLOGICAL_GROUP_BIOLOGICAL_SAMPLE_ITEM EMPTY>
<!ATTLIST BIOLOGICAL_GROUP_BIOLOGICAL_SAMPLE_ITEM
    BIOLOGICAL_GROUP_ID CDATA #REQUIRED
    BIOLOGICAL_SAMPLE_ID CDATA #REQUIRED
>

<!ELEMENT BIOLOGICAL_SAMPLE EMPTY>
<!ATTLIST BIOLOGICAL_SAMPLE
    ID CDATA #REQUIRED
    NUMBER CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    QUANTITATION_ID CDATA #REQUIRED
>

<!ELEMENT DOCUMENT EMPTY>
<!ATTLIST DOCUMENT
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    KEYWORDS CDATA #IMPLIED
    CREATION_TIMESTAMP CDATA #REQUIRED
    MODIFICATION_TIMESTAMP CDATA #IMPLIED
    CREATION_LOG CDATA #IMPLIED
    MODIFICATION_LOG CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    OBJECT_TREE_ID CDATA #REQUIRED
    VIRTUAL_FOLDER_ID CDATA #REQUIRED
    PROJECT_ID CDATA #REQUIRED
    SCHEMA_NAME CDATA #REQUIRED
>

<!ELEMENT ENZYME EMPTY>
<!ATTLIST ENZYME
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    CLEAVAGE_REGEXP CDATA #IMPLIED
    IS_INDEPENDANT CDATA #REQUIRED
    IS_SEMI_SPECIFIC CDATA #REQUIRED
>

<!ELEMENT ENZYME_CLEAVAGE EMPTY>
<!ATTLIST ENZYME_CLEAVAGE
    ID CDATA #REQUIRED
    SITE CDATA #REQUIRED
    RESIDUES CDATA #REQUIRED
    RESTRICTIVE_RESIDUES CDATA #IMPLIED
    ENZYME_ID CDATA #REQUIRED
>

<!ELEMENT EXTERNAL_DB EMPTY>
<!ATTLIST EXTERNAL_DB
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    CONNECTION_MODE CDATA #REQUIRED    
    HOST CDATA #IMPLIED
    PORT CDATA #IMPLIED
    USERNAME CDATA #IMPLIED
    PASSWORD CDATA #IMPLIED
    TYPE CDATA #REQUIRED
    VERSION CDATA #REQUIRED
    IS_BUSY CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
>

<!ELEMENT FRAGMENTATION_RULE EMPTY>
<!ATTLIST FRAGMENTATION_RULE
    ID CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    PRECURSOR_MIN_CHARGE CDATA #IMPLIED
    FRAGMENT_CHARGE CDATA #IMPLIED
    FRAGMENT_MAX_MOZ CDATA #IMPLIED
    FRAGMENT_RESIDUE_CONSTRAINT CDATA #IMPLIED
    REQUIRED_SERIE_QUALITY_LEVEL CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    THEORETICAL_FRAGMENT_ID CDATA #IMPLIED
    REQUIRED_SERIE_ID CDATA #IMPLIED
>

<!ELEMENT GROUP_SETUP EMPTY>
<!ATTLIST GROUP_SETUP
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    QUANTITATION_ID CDATA #REQUIRED
>

<!ELEMENT IDENTIFICATION EMPTY>
<!ATTLIST IDENTIFICATION
    ID CDATA #REQUIRED
    NUMBER CDATA #REQUIRED
    NAME CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    KEYWORDS CDATA #IMPLIED
    CREATION_TIMESTAMP CDATA #REQUIRED
    MODIFICATION_LOG CDATA #IMPLIED
    FRACTIONATION_TYPE CDATA #IMPLIED
    FRACTION_COUNT CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    ACTIVE_SUMMARY_ID CDATA #IMPLIED
    PROJECT_ID CDATA #REQUIRED
>

<!ELEMENT IDENTIFICATION_FRACTION EMPTY>
<!ATTLIST IDENTIFICATION_FRACTION
    ID CDATA #REQUIRED
    NUMBER CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    RESULT_SET_ID CDATA #REQUIRED
    IDENTIFICATION_ID CDATA #REQUIRED
    RUN_ID CDATA #IMPLIED
    RAW_FILE_NAME CDATA #IMPLIED
>

<!ELEMENT IDENTIFICATION_FRACTION_SUMMARY EMPTY>
<!ATTLIST IDENTIFICATION_FRACTION_SUMMARY
    ID CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    RESULT_SUMMARY_ID CDATA #REQUIRED
    IDENTIFICATION_FRACTION_ID CDATA #REQUIRED
    IDENTIFICATION_SUMMARY_ID CDATA #REQUIRED
>

<!ELEMENT IDENTIFICATION_SUMMARY EMPTY>
<!ATTLIST IDENTIFICATION_SUMMARY
    ID CDATA #REQUIRED
    NUMBER CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    RESULT_SUMMARY_ID CDATA #REQUIRED
    IDENTIFICATION_ID CDATA #REQUIRED
>

<!ELEMENT INSTRUMENT EMPTY>
<!ATTLIST INSTRUMENT
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SOURCE CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
>

<!ELEMENT INSTRUMENT_CONFIG EMPTY>
<!ATTLIST INSTRUMENT_CONFIG
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    MS1_ANALYZER CDATA #REQUIRED
    MSN_ANALYZER CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    INSTRUMENT_ID CDATA #REQUIRED
    ACTIVATION_TYPE CDATA #REQUIRED
>

<!ELEMENT INSTRUMENT_CONFIG_FRAGMENTATION_RULE_MAP EMPTY>
<!ATTLIST INSTRUMENT_CONFIG_FRAGMENTATION_RULE_MAP
    INSTRUMENT_CONFIG_ID CDATA #REQUIRED
    FRAGMENTATION_RULE_ID CDATA #REQUIRED
>

<!ELEMENT OBJECT_TREE EMPTY>
<!ATTLIST OBJECT_TREE
    ID CDATA #REQUIRED
    SERIALIZED_DATA CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    SCHEMA_NAME CDATA #REQUIRED
>

<!ELEMENT OBJECT_TREE_SCHEMA EMPTY>
<!ATTLIST OBJECT_TREE_SCHEMA
    NAME CDATA #REQUIRED
    TYPE CDATA #REQUIRED
    VERSION CDATA #IMPLIED
    SCHEMA CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
>

<!ELEMENT PEAKLIST_SOFTWARE EMPTY>
<!ATTLIST PEAKLIST_SOFTWARE
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    VERSION CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    SPEC_TITLE_PARSING_RULE_ID CDATA #REQUIRED
>

<!ELEMENT PROJECT EMPTY>
<!ATTLIST PROJECT
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    CREATION_TIMESTAMP CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    OWNER_ID CDATA #REQUIRED
>

<!ELEMENT PROJECT_DB_MAP EMPTY>
<!ATTLIST PROJECT_DB_MAP
    EXTERNAL_DB_ID CDATA #REQUIRED
    PROJECT_ID CDATA #REQUIRED
>

<!ELEMENT PROJECT_USER_ACCOUNT_MAP EMPTY>
<!ATTLIST PROJECT_USER_ACCOUNT_MAP
    PROJECT_ID CDATA #REQUIRED
    USER_ACCOUNT_ID CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
>

<!ELEMENT PROTEIN_MATCH_DECOY_RULE EMPTY>
<!ATTLIST PROTEIN_MATCH_DECOY_RULE
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    AC_DECOY_TAG CDATA #REQUIRED
>

<!ELEMENT QUANTITATION EMPTY>
<!ATTLIST QUANTITATION
    ID CDATA #REQUIRED
    NUMBER CDATA #REQUIRED
    NAME CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    KEYWORDS CDATA #IMPLIED
    CREATION_TIMESTAMP CDATA #REQUIRED
    MODIFICATION_LOG CDATA #IMPLIED
    FRACTION_COUNT CDATA #REQUIRED
    FRACTIONATION_TYPE CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    QUANT_METHOD_ID CDATA #REQUIRED
    PROJECT_ID CDATA #REQUIRED
>

<!ELEMENT QUANTITATION_FRACTION EMPTY>
<!ATTLIST QUANTITATION_FRACTION
    ID CDATA #REQUIRED
    NUMBER CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    LCMS_MAP_SET_ID CDATA #IMPLIED
    QUANT_RESULT_SUMMARY_ID CDATA #IMPLIED
    QUANTITATION_ID CDATA #REQUIRED
>

<!ELEMENT QUANT_CHANNEL EMPTY>
<!ATTLIST QUANT_CHANNEL
    ID CDATA #REQUIRED
    NUMBER CDATA #REQUIRED
    CONTEXT_KEY CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    LCMS_MAP_ID CDATA #IMPLIED
    IDENT_RESULT_SUMMARY_ID CDATA #REQUIRED
    QUANT_RESULT_SUMMARY_ID CDATA #IMPLIED
    QUANT_LABEL_ID CDATA #IMPLIED
    SAMPLE_ANALYSIS_REPLICATE_ID CDATA #REQUIRED
    BIOLOGICAL_SAMPLE_ID CDATA #REQUIRED
    QUANTITATION_FRACTION_ID CDATA #REQUIRED
    QUANTITATION_ID CDATA #REQUIRED
>

<!ELEMENT QUANT_LABEL EMPTY>
<!ATTLIST QUANT_LABEL
    ID CDATA #REQUIRED
    TYPE CDATA #REQUIRED
    NAME CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    QUANT_METHOD_ID CDATA #REQUIRED
>

<!ELEMENT QUANT_METHOD EMPTY>
<!ATTLIST QUANT_METHOD
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    TYPE CDATA #REQUIRED
    ABUNDANCE_UNIT CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
>

<!ELEMENT RATIO_DEFINITION EMPTY>
<!ATTLIST RATIO_DEFINITION
    ID CDATA #REQUIRED
    NUMBER CDATA #REQUIRED
    NUMERATOR_ID CDATA #REQUIRED
    DENOMINATOR_ID CDATA #REQUIRED
    GROUP_SETUP_ID CDATA #REQUIRED
>

<!ELEMENT RAW_FILE EMPTY>
<!ATTLIST RAW_FILE
    NAME CDATA #REQUIRED
    EXTENSION CDATA #REQUIRED
    DIRECTORY CDATA #IMPLIED
    CREATION_TIMESTAMP CDATA #IMPLIED
    INSTRUMENT_ID CDATA #REQUIRED
    OWNER_ID CDATA #REQUIRED
>

<!ELEMENT RUN EMPTY>
<!ATTLIST RUN
    ID CDATA #REQUIRED
    NUMBER CDATA #REQUIRED
    RUN_START CDATA #REQUIRED
    RUN_STOP CDATA #REQUIRED
    DURATION CDATA #REQUIRED
    LC_METHOD CDATA #IMPLIED
    MS_METHOD CDATA #IMPLIED
    ANALYST CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    RAW_FILE_NAME CDATA #REQUIRED
>

<!ELEMENT SAMPLE_ANALYSIS_REPLICATE EMPTY>
<!ATTLIST SAMPLE_ANALYSIS_REPLICATE
    ID CDATA #REQUIRED
    NUMBER CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    BIOLOGICAL_SAMPLE_ID CDATA #REQUIRED
    QUANTITATION_ID CDATA #REQUIRED
>

<!ELEMENT SCHEMA_VERSION EMPTY>
<!ATTLIST SCHEMA_VERSION
    VERSION CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
    TYPE CDATA #REQUIRED
    SCRIPT CDATA #REQUIRED
    CHECKSUM CDATA #IMPLIED
    INSTALLED_BY CDATA #REQUIRED
    INSTALLED_ON CDATA #IMPLIED
    EXECUTION_TIME CDATA #IMPLIED
    STATE CDATA #REQUIRED
    CURRENT_VERSION CDATA #REQUIRED
>

<!ELEMENT SPEC_TITLE_PARSING_RULE EMPTY>
<!ATTLIST SPEC_TITLE_PARSING_RULE
    ID CDATA #REQUIRED
    RAW_FILE_NAME CDATA #IMPLIED
    FIRST_CYCLE CDATA #IMPLIED
    LAST_CYCLE CDATA #IMPLIED
    FIRST_SCAN CDATA #IMPLIED
    LAST_SCAN CDATA #IMPLIED
    FIRST_TIME CDATA #IMPLIED
    LAST_TIME CDATA #IMPLIED
    NAME CDATA #REQUIRED
>

<!ELEMENT THEORETICAL_FRAGMENT EMPTY>
<!ATTLIST THEORETICAL_FRAGMENT
    ID CDATA #REQUIRED
    TYPE CDATA #IMPLIED
    NEUTRAL_LOSS CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
>

<!ELEMENT USER_ACCOUNT EMPTY>
<!ATTLIST USER_ACCOUNT
    ID CDATA #REQUIRED
    LOGIN CDATA #REQUIRED
    CREATION_MODE CDATA #REQUIRED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
>

<!ELEMENT VIRTUAL_FOLDER EMPTY>
<!ATTLIST VIRTUAL_FOLDER
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    PATH CDATA #IMPLIED
    SERIALIZED_PROPERTIES CDATA #IMPLIED
    PARENT_VIRTUAL_FOLDER_ID CDATA #IMPLIED
    PROJECT_ID CDATA #REQUIRED
>

=== profiproteomics/proline-server/pm-msdiag/src/test/resources/datasets/UDS_Simple_Dataset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "uds-dataset.dtd">
<dataset>
	<USER_ACCOUNT ID="1" LOGIN="joe" CREATION_MODE="auto" PASSWORD_HASH="993bd037c1ae6b87ea5adb936e71fca01a3b5c0505855444afdfa2f86405db1d"/> <!-- proline_pswd -->
	<USER_ACCOUNT ID="2" LOGIN="jack" CREATION_MODE="auto" PASSWORD_HASH="993bd037c1ae6b87ea5adb936e71fca01a3b5c0505855444afdfa2f86405db1d"/> <!-- proline_pswd -->
	<USER_ACCOUNT ID="3" LOGIN="jim" CREATION_MODE="auto" PASSWORD_HASH="993bd037c1ae6b87ea5adb936e71fca01a3b5c0505855444afdfa2f86405db1d"/> <!-- proline_pswd -->
	<PROJECT ID="1" NAME="joe's project" DESCRIPTION="joe's first project" CREATION_TIMESTAMP="2011-03-24 12:00:30" OWNER_ID="1" />
	<PROJECT_USER_ACCOUNT_MAP PROJECT_ID="1" USER_ACCOUNT_ID="1" />
	<PROJECT_USER_ACCOUNT_MAP PROJECT_ID="1" USER_ACCOUNT_ID="2" />
	<INSTRUMENT ID="1" SOURCE="ESI" NAME="VENUS"/>
	<VIRTUAL_FOLDER ID="1" PROJECT_ID="1" PATH="" NAME="Meetins"/>
	<VIRTUAL_FOLDER ID="2" PROJECT_ID="1" PARENT_VIRTUAL_FOLDER_ID="1" NAME="Boston"/>
	<VIRTUAL_FOLDER ID="3" PROJECT_ID="1" PATH="" NAME="Accessions lists"/>
	<OBJECT_TREE_SCHEMA SCHEMA="no schema" VERSION="1.0" NAME="text/csv" TYPE="csv"/>
	<OBJECT_TREE ID="1" SERIALIZED_DATA="HS90B_HUMAN,Heat shock protein HSP 90-beta,12589" SCHEMA_NAME="text/csv"/>
	<DOCUMENT ID="1" PROJECT_ID="1" SCHEMA_NAME="text/csv" CREATION_TIMESTAMP="2011-04-02 12:00:30" VIRTUAL_FOLDER_ID="3" NAME="S1_Proteins" DESCRIPTION="List of proteins (accession) identified in Sample 1 (S1)" OBJECT_TREE_ID="1"/>
	<RAW_FILE NAME="CAVEN456" OWNER_ID="1" INSTRUMENT_ID="1" EXTENSION="raw"/>
	<RAW_FILE NAME="CAVEN457" OWNER_ID="1" INSTRUMENT_ID="1" EXTENSION="raw"/>
	<RUN ID="1" RAW_FILE_NAME="CAVEN456" RUN_START="5" DURATION="85" RUN_STOP="90" NUMBER="1"/>
	<RUN ID="2" RAW_FILE_NAME="CAVEN457" RUN_START="5" DURATION="85" RUN_STOP="90" NUMBER="1"/>
	
	
	<DATA_SET NAME="CB_342" ID="1" PROJECT_ID="1" NUMBER="1" CHILDREN_COUNT="2" CREATION_TIMESTAMP="2011-03-24 14:00:30" TYPE="AGGREGATE"/>
	<DATA_SET NAME="CB_342_1" ID="2" PROJECT_ID="1" NUMBER="1" CHILDREN_COUNT="0" CREATION_TIMESTAMP="2011-03-24 15:00:30" TYPE="IDENTIFICATION" RESULT_SET_ID="789" RESULT_SUMMARY_ID="124" PARENT_DATASET_ID="1"/>
    <DATA_SET NAME="CB_342_2" ID="3" PROJECT_ID="1" NUMBER="1" CHILDREN_COUNT="0" CREATION_TIMESTAMP="2011-03-24 15:20:30" TYPE="IDENTIFICATION" RESULT_SET_ID="790" RESULT_SUMMARY_ID="125" PARENT_DATASET_ID="1"  />
    <RUN_IDENTIFICATION ID="2" RAW_FILE_NAME="CAVEN456" RUN_ID="1" />
    <RUN_IDENTIFICATION ID="3"  RAW_FILE_NAME="CAVEN457" RUN_ID="2"/>  
	
	<EXTERNAL_DB IS_BUSY="false"  VERSION="A.0.1" ID="1" TYPE="PDI"  USERNAME="sa" PASSWORD="myPass" NAME="pdi_test" CONNECTION_MODE="MEMORY"/>
	<EXTERNAL_DB IS_BUSY="false"  VERSION="A.0.1" ID="2" TYPE="PS"  USERNAME="sa" PASSWORD="myPass" NAME="ps_test" CONNECTION_MODE="MEMORY" />
	<EXTERNAL_DB IS_BUSY="false"  VERSION="A.0.1" ID="3" TYPE="MSI"  USERNAME="sa" PASSWORD="myPass" NAME="msi_test" CONNECTION_MODE="MEMORY" />
	<PROJECT_DB_MAP EXTERNAL_DB_ID="3" PROJECT_ID="1" />

	<!-- Needed for ResultSet Storer / ResultSetFakeBuilder test -->
	<SPEC_TITLE_PARSING_RULE ID="1" RAW_FILE_NAME="(.+)\.\d+\.\d+\.\d+\.dta" FIRST_SCAN=".+\.(\d+)\.\d+\.\d+\.dta" LAST_SCAN=".+\.\d+\.(\d+)\.\d+\.dta" NAME="extract_msn.exe"/>
	<SPEC_TITLE_PARSING_RULE ID="2" RAW_FILE_NAME="^File: (.+?)," FIRST_CYCLE="Cycle\(s\): (\d+) \(Experiment \d+\)|Cycle\(s\): (\d+), \d+" LAST_CYCLE="Cycle\(s\): (\d+) \(Experiment \d+\)|Cycle\(s\): \d+, (\d+)" FIRST_TIME="Elution: (.+?) to .+? min|Elution: (.+?) min" LAST_TIME="Elution: .+? to (.+?) min|Elution: (.+?) min" NAME="mascot.dll"/>
	<SPEC_TITLE_PARSING_RULE ID="3" RAW_FILE_NAME="\[(.+?)\]" FIRST_CYCLE="(\d+?) \(rt=" LAST_CYCLE="- \d+: Scan (\d+?) \(rt=" FIRST_TIME="\(rt=(\d+?\.\d+?)\)" LAST_TIME="-.+Scan \d+ \(rt=(\d+\.\d+)" NAME="Mascot Distiller"/>
	<SPEC_TITLE_PARSING_RULE ID="4" RAW_FILE_NAME="^RawFile: (.+?) FinneganScanNumber:" FIRST_SCAN="FinneganScanNumber: (\d+)" LAST_SCAN="FinneganScanNumber: (\d+)" NAME="MaxQuant"/>
	<SPEC_TITLE_PARSING_RULE ID="5" FIRST_SCAN="Spectrum\d+\s+scans:(\d+?)," LAST_SCAN="Spectrum\d+\s+scans:(\d+?)," NAME="Proteome Discoverer"/>
	<SPEC_TITLE_PARSING_RULE ID="6" FIRST_SCAN="scan=(\d+)" LAST_SCAN="scan=(\d+)" NAME="ProteoWizard 2.0"/>
	<SPEC_TITLE_PARSING_RULE ID="7" RAW_FILE_NAME="(.+)\.\d+\.\d+\.\d+$" FIRST_SCAN=".+\.(\d+)\.\d+\.\d+$" LAST_SCAN=".+\.\d+\.(\d+)\.\d+$" NAME="ProteoWizard 2.1"/>
	<SPEC_TITLE_PARSING_RULE ID="8" FIRST_TIME="Cmpd.+MS.+, (\d+\.\d+)(?:-\d+\.\d+)? min" LAST_TIME="Cmpd.+MS.+, (?:\d+\.\d+-)?(\d+\.\d+) min" NAME="Spectrum Mill/Bruker"/>
	<PEAKLIST_SOFTWARE ID="1" NAME="extract_msn.exe" SPEC_TITLE_PARSING_RULE_ID="1"/>
	<PEAKLIST_SOFTWARE ID="2" NAME="mascot.dll" SPEC_TITLE_PARSING_RULE_ID="2"/>
	<PEAKLIST_SOFTWARE ID="3" NAME="Mascot Distiller" SPEC_TITLE_PARSING_RULE_ID="3"/>
	<PEAKLIST_SOFTWARE ID="4" NAME="MaxQuant" SPEC_TITLE_PARSING_RULE_ID="4"/>
	<PEAKLIST_SOFTWARE ID="5" NAME="Proteome Discoverer" SPEC_TITLE_PARSING_RULE_ID="5"/>
	<PEAKLIST_SOFTWARE ID="6" NAME="ProteoWizard" VERSION="2.0" SPEC_TITLE_PARSING_RULE_ID="6"/>
	<PEAKLIST_SOFTWARE ID="7" NAME="ProteoWizard" VERSION="2.1" SPEC_TITLE_PARSING_RULE_ID="7"/>
	<PEAKLIST_SOFTWARE ID="8" NAME="Spectrum Mill/Bruker" SPEC_TITLE_PARSING_RULE_ID="8"/>


	<ACTIVATION TYPE="CID"/>
	<INSTRUMENT_CONFIG ID="1" MS1_ANALYZER="Analyzer" NAME="VENUS_CFG" ACTIVATION_TYPE="CID" INSTRUMENT_ID="1" />

	<ENZYME ID="1" IS_SEMI_SPECIFIC="false" IS_INDEPENDANT="true" NAME="Trypsin" />
	<ENZYME ID="2" IS_SEMI_SPECIFIC="true" IS_INDEPENDANT="true" NAME="Trypsin/P" />


</dataset>

=== profiproteomics/proline-server/pm-mascot-parser/src/test/resources/fr/proline/module/parser/mascot/UDS_Simple_Dataset_SQLite.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "../../../../../uds-dataset.dtd">
<dataset>
	<USER_ACCOUNT ID="1" LOGIN="joe" CREATION_MODE="auto"/>
	<USER_ACCOUNT ID="2" LOGIN="jack" CREATION_MODE="auto"/>
	<USER_ACCOUNT ID="3" LOGIN="jim" CREATION_MODE="auto"/>
	<PROJECT ID="1" NAME="joe's project" DESCRIPTION="joe's first project" CREATION_TIMESTAMP="2011-03-24 12:00:30" OWNER_ID="1" />
	<PROJECT_USER_ACCOUNT_MAP PROJECT_ID="1" USER_ACCOUNT_ID="1" />
	<PROJECT_USER_ACCOUNT_MAP PROJECT_ID="1" USER_ACCOUNT_ID="2" />
	<INSTRUMENT ID="1" SOURCE="ESI" NAME="VENUS"/>
	<VIRTUAL_FOLDER ID="1" PROJECT_ID="1" PATH="" NAME="Meetins"/>
	<VIRTUAL_FOLDER ID="2" PROJECT_ID="1" PARENT_VIRTUAL_FOLDER_ID="1" NAME="Boston"/>
	<VIRTUAL_FOLDER ID="3" PROJECT_ID="1" PATH="" NAME="Accessions lists"/>
	<OBJECT_TREE_SCHEMA SCHEMA="no schema" VERSION="1.0" NAME="text/csv" TYPE="csv"/>
	<OBJECT_TREE ID="1" SERIALIZED_DATA="HS90B_HUMAN,Heat shock protein HSP 90-beta,12589" SCHEMA_NAME="text/csv"/>
	<DOCUMENT ID="1" PROJECT_ID="1" SCHEMA_NAME="text/csv" CREATION_TIMESTAMP="2011-04-02 12:00:30" VIRTUAL_FOLDER_ID="3" NAME="S1_Proteins" DESCRIPTION="List of proteins (accession) identified in Sample 1 (S1)" OBJECT_TREE_ID="1"/>
	<RAW_FILE NAME="CAVEN456" OWNER_ID="1" INSTRUMENT_ID="1" EXTENSION="raw"/>
	<RAW_FILE NAME="CAVEN457" OWNER_ID="1" INSTRUMENT_ID="1" EXTENSION="raw"/>
	<RUN ID="1" RAW_FILE_NAME="CAVEN456" RUN_START="5" DURATION="85" RUN_STOP="90" NUMBER="1"/>
	<RUN ID="2" RAW_FILE_NAME="CAVEN457" RUN_START="5" DURATION="85" RUN_STOP="90" NUMBER="1"/>
	<IDENTIFICATION NAME="CB_342" ID="1" PROJECT_ID="1" NUMBER="1" FRACTION_COUNT="2" CREATION_TIMESTAMP="2011-03-24 14:00:30" />
	<IDENTIFICATION_FRACTION ID="1" NUMBER="1" IDENTIFICATION_ID="1" RESULT_SET_ID="789" RAW_FILE_NAME="CAVEN456" RUN_ID="1"/>
	<IDENTIFICATION_FRACTION ID="2" NUMBER="2" IDENTIFICATION_ID="1" RESULT_SET_ID="790" RAW_FILE_NAME="CAVEN457" RUN_ID="2"/>
	<IDENTIFICATION_SUMMARY ID="1" NUMBER="1" IDENTIFICATION_ID="1" RESULT_SUMMARY_ID="123"/>
	<IDENTIFICATION_FRACTION_SUMMARY ID="1" IDENTIFICATION_FRACTION_ID="1" RESULT_SUMMARY_ID="124" IDENTIFICATION_SUMMARY_ID="1"/>
	<IDENTIFICATION_FRACTION_SUMMARY ID="2" IDENTIFICATION_FRACTION_ID="2" RESULT_SUMMARY_ID="125" IDENTIFICATION_SUMMARY_ID="1"/>
	<EXTERNAL_DB IS_BUSY="false"  VERSION="A.0.1" ID="1" TYPE="PDI"  USERNAME="" PASSWORD="" NAME="pdi_sqlite_shared_memory.lock:pdi_test?mode=memory&amp;cache=shared" CONNECTION_MODE="FILE"/>
	<EXTERNAL_DB IS_BUSY="false"  VERSION="A.0.1" ID="2" TYPE="PS"  USERNAME="" PASSWORD="" NAME="ps_sqlite_shared_memory.lock:ps_test?mode=memory&amp;cache=shared" CONNECTION_MODE="FILE" />
	<EXTERNAL_DB IS_BUSY="false"  VERSION="A.0.1" ID="3" TYPE="MSI"  USERNAME="" PASSWORD="" NAME="msi_sqlite_shared_memory.lock:msi_test?mode=memory&amp;cache=shared" CONNECTION_MODE="FILE" />
	<PROJECT_DB_MAP EXTERNAL_DB_ID="3" PROJECT_ID="1" />

	<!-- Needed for ResultSet Storer / ResultSetFakeBuilder test -->
	<SPEC_TITLE_PARSING_RULE ID="1" NAME="ZZZ Distiller TEST" />
	<PEAKLIST_SOFTWARE ID="1"  VERSION="4.3.2" NAME="Distiller" SPEC_TITLE_PARSING_RULE_ID="1" />


	<ACTIVATION TYPE="1"/>
	<INSTRUMENT_CONFIG ID="1" MS1_ANALYZER="Analyzer" NAME="VENUS_CFG" ACTIVATION_TYPE="1" INSTRUMENT_ID="1" />

	<ENZYME ID="1" IS_SEMI_SPECIFIC="false" IS_INDEPENDANT="true" NAME="TRYPSIC" />
	<ENZYME ID="2" IS_SEMI_SPECIFIC="true" IS_INDEPENDANT="true" NAME="Trypsin/P" />


</dataset>
